services:
    revinate_analytics.routing_loader:
        class: Revinate\AnalyticsBundle\Routing\RoutingLoader
        arguments: [@service_container]
        tags:
            - { name: routing.loader }
